# Numpy Cheat Sheet

* numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
    * subok: bool, optional
        * If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array (default).

    * ndmin: int, optional
        * Specifies the minimum number of dimensions that the resulting array should have. Ones will be prepended to the shape as needed to meet this requirement.

##### fill with 0,1 and any numbers
* numpy.zeros(shape, dtype=float, order='C', *, like=None)
* numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)

* numpy.ones(shape, dtype=None, order='C', *, like=None)
* numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None

* numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
* numpy.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)

##### fill with random number
* numpy.random.rand(d0, d1, ..., dn) : r,c
* numpy.random.random_sample(size=None)
* numpy.random.randint(low, high=None, size=None, dtype='l')

##### identity matrix
* numpy.identity(n, dtype=None, *, like=None)

#### Product of two arrays
* numpy.matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis]) = <ufunc 'matmul'>

# Basic Code

In [108]:
import numpy as np

In [109]:
# Created 1 and 2 Dimentional Array
a = np.array([1,2,3])
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(a)
print(b)


[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [110]:
# Get Dimension
print(a.ndim, b.ndim)

# Get Shape
print(b.shape)

# Get Type
print(a.dtype)
print(b.dtype)

# Get Size
print("{}byte".format(a.itemsize))
print("{}byte".format(b.itemsize))

# Get total Size
print("{} and {}".format(a.size*a.itemsize, a.nbytes))

1 2
(2, 3)
int32
float64
4byte
8byte
12 and 12


# Accessing/Changing Specific elements, rows, columns, etc

In [111]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(c)
print(c.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [112]:
# Get a specific element [r, c]
print(c[1,5])

# Get a specific row
print(c[0,:])

# Get a specific column
print(c[:,1])

# Getting a little more fancy[Starindex:endindex:stepsize]
print(c[0,1:6:2])

# Change value
c[1,5] = 20
print(c)

c[:,2] = 5
print(c)

13
[1 2 3 4 5 6 7]
[2 9]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# 3-D example

In [113]:
d = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(d)

# Get specific element(work outside in)
print(d[0,1,1])

# replace
d[:,1,:] = [[9,9],[8,8]]
print(d[:,1,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[9 9]
 [8 8]]


# Initializing Different Types of Arrays

In [114]:
# ALL 0s matirx
print(np.zeros((2,3)))

#All 1s matrix
print(np.ones((4,2,2), dtype = "int32"))

# any other number
print(np.full((2,2), 99))
print(np.full_like(b, 4))

# Random decimal numbers
print(np.random.rand(4,2,3))
print(np.random.random_sample(a.shape))
print(np.random.randint(2,7, size=(3,3)))

# The identity matirix
print(np.identity(5))

# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

# quiz

output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)



[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[99 99]
 [99 99]]
[[4. 4. 4.]
 [4. 4. 4.]]
[[[0.39454457 0.35014774 0.77675947]
  [0.35063587 0.15402982 0.83446354]]

 [[0.02819946 0.23047527 0.48617363]
  [0.04466469 0.53278247 0.67995809]]

 [[0.28597198 0.8340969  0.56537557]
  [0.8869784  0.27026602 0.10496383]]

 [[0.6122192  0.57937914 0.10619427]
  [0.16013051 0.61094076 0.96200905]]]
[0.10471646 0.96825135 0.21315855]
[[3 5 2]
 [6 3 5]
 [2 2 3]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [115]:
# contents of e is changed
e = np.array([1,2,3])
f = e 
f[0] = 100
print(f)
print(e)
# contents of g is not changed
g = np.array([1,2,3])
h = g.copy() 
h[0] = 100
print(g)
print(h)



[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]


# Mathmatics

In [116]:
i = np.array([1,2,3,4])
print(i)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

print(np.cos(a))


[1 2 3 4]
[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[ 0.54030231 -0.41614684 -0.9899925 ]


#### Linear Algebra

In [117]:
j = np.ones((2,3))
k = np.full((3,2),2)

print(j)
print(k)

print(np.matmul(j,k))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
