# Numpy Cheat Sheet

* numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
    * subok: bool, optional
        * If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array (default).

    * ndmin: int, optional
        * Specifies the minimum number of dimensions that the resulting array should have. Ones will be prepended to the shape as needed to meet this requirement.

* numpy.zeros(shape, dtype=float, order='C', *, like=None)


# Basic Code

In [1]:
import numpy as np

In [10]:
# Created 1 and 2 Dimentional Array
a = np.array([1,2,3])
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(a)
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [24]:
# Get Dimension
print(a.ndim, b.ndim)

# Get Shape
print(b.shape)

# Get Type
print(a.dtype)
print(b.dtype)

# Get Size
print("{}byte".format(a.itemsize))
print("{}byte".format(b.itemsize))

# Get total Size
print("{} and {}".format(a.size*a.itemsize, a.nbytes))

1 2
(2, 3)
int32
float64
4byte
8byte
12 and 12


# Accessing/Changing Specific elements, rows, columns, etc

In [27]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(c)
print(c.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [41]:
# Get a specific element [r, c]
print(c[1,5])

# Get a specific row
print(c[0,:])

# Get a specific column
print(c[:,1])

# Getting a little more fancy[Starindex:endindex:stepsize]
print(c[0,1:6:2])

# Change value
c[1,5] = 20
print(c)

c[:,2] = 5
print(c)

20
[1 2 5 4 5 6 7]
[2 9]
[2 4 6]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# 3-D example

In [48]:
b = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(b)

# Get specific element(work outside in)
print(b[0,1,1])

# replace
b[:,1,:] = [[9,9],[8,8]]
print(b[:,1,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[9 9]
 [8 8]]


# Initializing Different Types of Arrays

In [ ]:
# ALL 0s matirx