# Basic Code

In [2]:
import numpy as np

In [3]:
# Created 1 and 2 Dimentional Array
a = np.array([1,2,3])
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(a)
print(b)


[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
print(a.ndim, b.ndim)

# Get Shape
print(b.shape)

# Get Type
print(a.dtype)
print(b.dtype)

# Get Size
print("{}byte".format(a.itemsize))
print("{}byte".format(b.itemsize))

# Get total Size
print("{} and {}".format(a.size*a.itemsize, a.nbytes))

1 2
(2, 3)
int32
float64
4byte
8byte
12 and 12


# Accessing/Changing Specific elements, rows, columns, etc

In [5]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(c)
print(c.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [6]:
# Get a specific element [r, c]
print(c[1,5])

# Get a specific row
print(c[0,:])

# Get a specific column
print(c[:,1])

# Getting a little more fancy[Starindex:endindex:stepsize]
print(c[0,1:6:2])

# Change value
c[1,5] = 20
print(c)

c[:,2] = 5
print(c)

13
[1 2 3 4 5 6 7]
[2 9]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# 3-D example

In [7]:
d = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(d)

# Get specific element(work outside in)
print(d[0,1,1])

# replace
d[:,1,:] = [[9,9],[8,8]]
print(d[:,1,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[9 9]
 [8 8]]


# Initializing Different Types of Arrays

In [8]:
# ALL 0s matirx
print(np.zeros((2,3)))

#All 1s matrix
print(np.ones((4,2,2), dtype = "int32"))

# any other number
print(np.full((2,2), 99))
print(np.full_like(b, 4))

# Random decimal numbers
print(np.random.rand(4,2,3))
print(np.random.random_sample(a.shape))
print(np.random.randint(2,7, size=(3,3)))

# The identity matirix
print(np.identity(5))

# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

# quiz

output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)



[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[99 99]
 [99 99]]
[[4. 4. 4.]
 [4. 4. 4.]]
[[[0.18920673 0.73194093 0.06060167]
  [0.3870808  0.99684914 0.11290901]]

 [[0.9735059  0.37448671 0.03463227]
  [0.11325576 0.80079407 0.29389814]]

 [[0.43388957 0.4274427  0.43287362]
  [0.66804446 0.82682971 0.45469483]]

 [[0.99805968 0.06152188 0.82397954]
  [0.44009244 0.8747555  0.7574278 ]]]
[0.89281431 0.38018995 0.01910197]
[[2 5 2]
 [4 5 4]
 [4 3 2]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [9]:
# contents of e is changed
e = np.array([1,2,3])
f = e 
f[0] = 100
print(f)
print(e)
# contents of g is not changed
g = np.array([1,2,3])
h = g.copy() 
h[0] = 100
print(g)
print(h)



[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]


# Mathmatics

In [10]:
i = np.array([1,2,3,4])
print(i)
print(a+2)
print(a-2)
print(a*2)
print(a/2)

print(np.cos(a))


[1 2 3 4]
[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[ 0.54030231 -0.41614684 -0.9899925 ]


#### Linear Algebra

In [11]:
# product of  two arrays
j = np.ones((2,3))
k = np.full((3,2),2)
print(j)
print(k)
print(np.matmul(j,k))

# Find the determinant

l = np.identity(3)
print(l)
print(np.linalg.det(l))




[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


# Statistics

In [12]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)


# min max
print(np.min(stats,axis=1))
print(np.max(stats))

# sum
print(np.sum(stats, axis = 1))

[[1 2 3]
 [4 5 6]]
[1 4]
6
[ 6 15]


# Reorganizing Arrays

In [13]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

# vertically & horizontally stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print(np.hstack([v1,v2]))


[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


# Miscellaneous

In [19]:
# load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766   4  55   6   5   3   4   5   6   7   8  11  12  15]
 [  1   2  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Advanced Indexing

In [34]:
## you can index with a list in Numpy
m = np.array([1,2,3,4,5,6,7,8,9])
m[[1,2,8]]


print(filedata > 50)
print("\n")
print(filedata[filedata >50])
print("\n")
print(np.any(filedata > 50, axis = 0))
print("\n")
print(np.all(filedata > 50, axis = 0))
print("\n")
print((filedata > 50) & (filedata < 100))


[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True False  True False False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


[196  75 766  55 999  78  76  88]


[False False False False  True  True  True False  True False False False
 False False False False  True  True]


[False False False False  True False False False False False False False
 False False False False False False]


[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False False  True False False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]




array([2, 3, 9])